#### 1. Import pandas library

In [49]:
import pandas as pd
import numpy as np

#### 2. Import users table:

In [2]:
users = pd.read_csv('users_table.csv')
users.shape

(40325, 14)

#### 3. Rename Id column to userId

In [20]:
users.rename(columns={'Id': 'userId'}, inplace= True)
users.dtypes

userID               int64
Reputation           int64
CreationDate        object
DisplayName         object
LastAccessDate      object
WebsiteUrl          object
Location            object
AboutMe             object
Views                int64
UpVotes              int64
DownVotes            int64
AccountId            int64
Age                float64
ProfileImageUrl     object
dtype: object

In [21]:
users.rename

<bound method DataFrame.rename of        userID  Reputation     CreationDate     DisplayName    LastAccessDate  \
0          -1           1   7/19/2010 6:55       Community    7/19/2010 6:55
1           2         101  7/19/2010 14:01    Geoff Dalgas  11/12/2013 22:07
2           3         101  7/19/2010 15:34    Jarrod Dixon     8/8/2014 6:42
3           4         101  7/19/2010 19:03          Emmett     1/2/2014 9:31
4           5        6792  7/19/2010 19:03           Shane    8/13/2014 0:23
...       ...         ...              ...             ...               ...
40320   55743           1  9/13/2014 21:03       AussieMeg   9/13/2014 21:18
40321   55744           6  9/13/2014 21:39       Mia Maria   9/13/2014 21:39
40322   55745         101  9/13/2014 23:45    tronbabylove   9/13/2014 23:45
40323   55746         106   9/14/2014 0:29             GPP    9/14/2014 2:05
40324   55747           1   9/14/2014 1:01  Shivam Agrawal    9/14/2014 1:19

                           WebsiteUrl            Location  \
0      http://meta.stackexchange.com/  on the server farm
1            http://stackoverflow.com       Corvallis, OR
2            http://stackoverflow.com        New York, NY
3        http://minesweeperonline.com   San Francisco, CA
4             http://www.statalgo.com        New York, NY
...                               ...                 ...
40320                             NaN                 NaN
40321                             NaN                 NaN
40322                             NaN       United States
40323                             NaN                 NaN
40324                             NaN               India

                                                 AboutMe  Views  UpVotes  \
0      <p>Hi, I'm not really a person.</p>\r\n\r\n<p>...      0     5007
1      <p>Developer on the StackOverflow team.  Find ...     25        3
2      <p><a href="http://blog.stackoverflow.com/2009...     22       19
3      <p>currently at a startup in SF</p>\r\n\r\n<p>...     11        0
4      <p>Quantitative researcher focusing on statist...   1145      662
...                                                  ...    ...      ...
40320                                                NaN      0        0
40321                                                NaN      1        0
40322                                                NaN      0        0
40323  <p>Stats noobie, product, marketing &amp; medi...      1        0
40324                       <p>Maths Enthusiast </p>\r\n      0        0

       DownVotes  AccountId   Age  \
0           1920         -1   NaN
1              0          2  37.0
2              0          3  35.0
3              0       1998  28.0
4              5      54503  35.0
...          ...        ...   ...
40320          0    5026902   NaN
40321          0    5026998   NaN
40322          0     481766   NaN
40323          0     976289   NaN
40324          0    5027354   NaN

                                         ProfileImageUrl
0                                                    NaN
1                                                    NaN
2                                                    NaN
3                     http://i.stack.imgur.com/d1oHX.jpg
4                                                    NaN
...                                                  ...
40320  http://graph.facebook.com/665821703/picture?ty...
40321                                                NaN
40322  https://www.gravatar.com/avatar/faa7a3fdbd8308...
40323  https://www.gravatar.com/avatar/6d9e9fa6b783a3...
40324  https://lh4.googleusercontent.com/-ZsXhwVaFmiY...

[40325 rows x 14 columns]>

#### 4. Import posts table:

In [22]:
posts = pd.read_csv('posts_table.csv')

C:\Users\Angela\AppData\Local\Temp\ipykernel_14684\4113675704.py:1: DtypeWarning: Columns (0,1,2,4,5,7,11,12,13,14) have mixed types. Specify dtype option on import or set low_memory=False.
  posts = pd.read_csv('posts_table.csv')

In [23]:
posts

,Id,PostTypeId,AcceptedAnswerId,CreaionDate,Score,ViewCount,Body,OwnerUserId,LasActivityDate,Title,...,AnswerCount,CommentCount,FavoriteCount,LastEditorUserId,LastEditDate,CommunityOwnedDate,ParentId,ClosedDate,OwnerDisplayName,LastEditorDisplayName
0,1,1,15,7/19/2010 19:12,23,1278,<p>How should I elicit prior distributions fro...,8,9/15/2010 21:08,Eliciting priors from experts,...,5,1,14,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,1,59,7/19/2010 19:12,22,8198,<p>In many different statistical methods there...,24,11/12/2012 9:21,What is normality?,...,7,1,8,88,8/7/2010 17:56,NaN,NaN,NaN,NaN,NaN
2,3,1,5,7/19/2010 19:13,54,3613,<p>What are some valuable Statistical Analysis...,18,5/27/2013 14:48,What are some valuable Statistical Analysis op...,...,19,4,36,183,2/12/2011 5:50,7/19/2010 19:13,NaN,NaN,NaN,NaN
3,4,1,135,7/19/2010 19:13,13,5224,<p>I have two groups of data. Each with a dif...,23,9/8/2010 3:00,Assessing the significance of differences in d...,...,5,2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,2,NaN,7/19/2010 19:14,81,NaN,"<p>The R-project</p>\n\n<p><a href=""http://www...",23,7/19/2010 19:21,NaN,...,NaN,3,NaN,23,7/19/2010 19:21,7/19/2010 19:14,3.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40480,48321,2,NaN,1/23/2013 9:00,0,NaN,<p>you can use the matlab codes for svm and co...,19966.0,1/23/2013 9:00,NaN,...,NaN,0,NaN,NaN,NaN,NaN,45118.0,NaN,NaN,NaN
40481,48322,2,NaN,1/23/2013 9:09,3,NaN,"<p>I use <a href=""http://www.gnu.org/software/...",892.0,1/23/2013 13:13,NaN,...,NaN,2,NaN,892.0,1/23/2013 13:13,NaN,48311.0,NaN,NaN,NaN
40482,48323,2,NaN,1/23/2013 9:16,1,NaN,"<p>If I understand your question correctly, yo...",2020.0,1/23/2013 9:16,NaN,...,NaN,0,NaN,NaN,NaN,NaN,48247.0,NaN,NaN,NaN
40483,48324,2,NaN,1/23/2013 9:36,3,NaN,"<p>Doesn't really help you with your question,...",19914.0,1/23/2013 9:36,NaN,...,NaN,0,NaN,NaN,NaN,NaN,48297.0,NaN,NaN,NaN
40484,48325,1,NaN,1/23/2013 9:44,-1,116.0,"<p>I have 10 vectors each having 100,000 point...",19968.0,2/22/2013 11:23,are data sets obtained from a Normal distribut...,...,2.0,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#### 5. Rename Id column to postId and OwnerUserId to userId

In [28]:
posts.rename(columns = {'Id': 'postId', 'OwnerUserId': 'userId'}, inplace= True)
posts.rename

<bound method DataFrame.rename of       postId PostTypeId AcceptedAnswerId      CreaionDate Score ViewCount  \
0          1          1               15  7/19/2010 19:12    23      1278
1          2          1               59  7/19/2010 19:12    22      8198
2          3          1                5  7/19/2010 19:13    54      3613
3          4          1              135  7/19/2010 19:13    13      5224
4          5          2              NaN  7/19/2010 19:14    81       NaN
...      ...        ...              ...              ...   ...       ...
40480  48321          2              NaN   1/23/2013 9:00     0       NaN
40481  48322          2              NaN   1/23/2013 9:09     3       NaN
40482  48323          2              NaN   1/23/2013 9:16     1       NaN
40483  48324          2              NaN   1/23/2013 9:36     3       NaN
40484  48325          1              NaN   1/23/2013 9:44    -1     116.0

                                                    Body   userId  \
0      <p>How should I elicit prior distributions fro...        8
1      <p>In many different statistical methods there...       24
2      <p>What are some valuable Statistical Analysis...       18
3      <p>I have two groups of data.  Each with a dif...       23
4      <p>The R-project</p>\n\n<p><a href="http://www...       23
...                                                  ...      ...
40480  <p>you can use the matlab codes for svm and co...  19966.0
40481  <p>I use <a href="http://www.gnu.org/software/...    892.0
40482  <p>If I understand your question correctly, yo...   2020.0
40483  <p>Doesn't really help you with your question,...  19914.0
40484  <p>I have 10 vectors each having 100,000 point...  19968.0

       LasActivityDate                                              Title  \
0      9/15/2010 21:08                      Eliciting priors from experts
1      11/12/2012 9:21                                 What is normality?
2      5/27/2013 14:48  What are some valuable Statistical Analysis op...
3        9/8/2010 3:00  Assessing the significance of differences in d...
4      7/19/2010 19:21                                                NaN
...                ...                                                ...
40480   1/23/2013 9:00                                                NaN
40481  1/23/2013 13:13                                                NaN
40482   1/23/2013 9:16                                                NaN
40483   1/23/2013 9:36                                                NaN
40484  2/22/2013 11:23  are data sets obtained from a Normal distribut...

       ... AnswerCount CommentCount FavoriteCount LastEditorUserId  \
0      ...           5            1            14              NaN
1      ...           7            1             8               88
2      ...          19            4            36              183
3      ...           5            2             2              NaN
4      ...         NaN            3           NaN               23
...    ...         ...          ...           ...              ...
40480  ...         NaN            0           NaN              NaN
40481  ...         NaN            2           NaN            892.0
40482  ...         NaN            0           NaN              NaN
40483  ...         NaN            0           NaN              NaN
40484  ...         2.0            4           NaN              NaN

          LastEditDate CommunityOwnedDate ParentId  ClosedDate  \
0                  NaN                NaN      NaN         NaN
1       8/7/2010 17:56                NaN      NaN         NaN
2       2/12/2011 5:50    7/19/2010 19:13      NaN         NaN
3                  NaN                NaN      NaN         NaN
4      7/19/2010 19:21    7/19/2010 19:14      3.0         NaN
...                ...                ...      ...         ...
40480              NaN                NaN  45118.0         NaN
40481  1/23/2013 13:13                NaN  48311.0         NaN
40482              NaN                NaN  48247.0         NaN
40483              NaN                NaN  48297.0         NaN
40484              NaN                NaN      NaN         NaN

      OwnerDisplayName LastEditorDisplayName
0                  NaN                   NaN
1                  NaN                   NaN
2                  NaN                   NaN
3                  NaN                   NaN
4                  NaN                   NaN
...                ...                   ...
40480              NaN                   NaN
40481              NaN                   NaN
40482              NaN                   NaN
40483              NaN                   NaN
40484              NaN                   NaN

[40485 rows x 21 columns]>

#### 6. Define new dataframes for users and posts with the following selected columns:
    **users columns**: userId, Reputation,Views,UpVotes,DownVotes
    **posts columns**: postId, Score,userId,ViewCount,CommentCount

In [33]:
users = users[['userID', 'Reputation', 'Views', 'UpVotes', 'DownVotes']]
posts = posts[['postId', 'Score', 'userId', 'ViewCount', 'CommentCount']]

#### 7. Merge both dataframes, users and posts. 
You will need to make a [merge](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.merge.html) of posts and users dataframes.

In [48]:
users_posts = users.merge(posts, on='userId')

KeyError: 'userId'

#### 8. How many missing values do you have in your merged dataframe? On which columns?

In [44]:
print(users_posts.isnull().sum())

NameError: name 'users_posts' is not defined

#### 9. You will need to make something with missing values.  Will you clean or filling them? Explain. 
**Remember** to check the results of your code before passing to the next step

#### 10. Adjust the data types in order to avoid future issues. Which ones should be changed?